### ISSUE TITLE
koleton.custom.RecyclerKoletonView cannot be cast to androidx.recyclerview.widget.RecyclerView

### ISSUE THREAD

**Issue by keivanshamlu** [ericktijerou/koleton#24]
Undeliverable exception received, not sure what to do
    io.reactivex.exceptions.OnErrorNotImplementedException: koleton.custom.RecyclerKoletonView cannot be cast to androidx.recyclerview.widget.RecyclerView

hello , i'm trying to hide skleton from a view when api response received but when i call view.hideSkleton() i get this error ...

**Comment by ericktijerou** [comment]
Hi! @keivanshamlu. 

Sorry for the late reply. 

 I couldn't reproduce this issue. Can you please provide more information about your code?

Thank you for your feedback. It is appreciated.

**Comment by yesidlazaro** [comment]
i have same issue with android studio 4.2.1 kotlin 1.5.0 an recyclerview 1.2.0

**Comment by yesidlazaro** [comment]
@ericktijerou

**Comment by yesidlazaro** [comment]
@keivanshamlu i just downgraded to kotlin 1.4.30 and there is no crash.  be careful updating your build tools

**Comment by billypap1** [comment]
@ericktijerou @yesidlazaro  @keivanshamlu  Same issue here, with android studio 4.2.1 kotlin 1.5.0. I get this error in any type of view. Any other idea instead of downgrading version of Koltin?

**Comment by ericktijerou** [comment]
Hi @yesidlazaro @billypap1 @keivanshamlu. Sorry for the inconvenience.

I updated to Kotlin `1.5.10 `version

Thank you for your feedback, i appreciate it.

**Comment by drianmr** [comment]
This issue is still exists with Kotlin 1.5.32
