### ISSUE TITLE
[Bug] - RecyclerView skeleton inside BottomSheetDialogFragment

### ISSUE THREAD

**Issue by TurKurT656** [ericktijerou/koleton#25]
I have a BottomSheetDialogFragment with this layout:

```
<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        >

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/category_list"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tools:listitem="@layout/item_category"
            />

    </androidx.constraintlayout.widget.ConstraintLayout>
```
but calling `loadSkeleton` function does not show the skeleton on it. I've tried a simple textView and it worked but on RecyclerView nothing happens

**Comment by ericktijerou** [comment]
Hi! @TurKurT656 👋,

Sorry for the late reply.

I tried the skeleton inside of BottomSheetDialogFragment and the library works well, but i found an issue related with CardView/FrameLayout. Maybe you are using them in your `@layout/item_category`.

Please try out `0.8.2` version and let me know if your issue has been resolved.

Cheers!!
