### ISSUE TITLE
TextView doesn't set up data, skeleton screen can't show~

### ISSUE THREAD

**Issue by 15189611** [ericktijerou/koleton#27]
I have a situation where my view doesn't set up data in advance, I need to request data set up after the network, and the skeleton screen doesn't appear at this time

**Comment by ericktijerou** [comment]
@15189611 thanks, I appreciate your feedback.

If you use `textView.loadSkeleton()` function, please make sure that you are setting `android:text="@string/your_label"` in your xml. I'm working in a better solution for that.

Please let me know if the still issue persists.

**Comment by 15189611** [comment]
if i use textView doesn't setting android:text="@string/your_label" ,the skeleton doesn't working

**Comment by 15189611** [comment]
because android:text="" from Remote data！

**Comment by 15189611** [comment]
The skeleton framework can be support?

**Comment by ericktijerou** [comment]
Hi @15189611 👋,

I found some issues related with TextView's skeletons and added a new extension function for textviews. It is not necessary to set text in your xml. You just have to set length for skeleton to work well.

`textView?.loadSkeleton(length = 20)`

Please try out `0.8.5` version.

**Comment by 15189611** [comment]
if is other view or viewGroup doesn't setting data maybe couldn't support ?

**Comment by ericktijerou** [comment]
@15189611 There is no support for LinearLayouts and RelativeLayout. I'm working on that. 

The others Views and ViewGroups should work well.

**Comment by 15189611** [comment]
![Uploading image.png…]()
i can't setting android:layout_height="120dp" , the ImageView doesn't working~

**Comment by 15189611** [comment]
![WechatIMG94](https://user-images.githubusercontent.com/13620658/106694510-b579c400-6613-11eb-926e-34821eb5f9ef.png)

**Comment by 15189611** [comment]
I need to use your framework now because all my elemental data comes from the remote

**Comment by ericktijerou** [comment]
@15189611  I've tried to reproduce your problem but everything works fine. 

```
        <com.google.android.material.imageview.ShapeableImageView
            android:id="@+id/ivMap"
            android:layout_width="0dp"
            android:layout_height="120dp"
            android:scaleType="centerCrop"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:shapeAppearanceOverlay="@style/ShapeAppearance.RoundedCornerImageView"
            tools:srcCompat="@drawable/map_one" />
```

- `clHeader?.loadSkeleton()`

> <img src="https://user-images.githubusercontent.com/17746153/106696362-93982700-65aa-11eb-9d14-958f2d352020.jpeg" width="200">


- `ivMap?.loadSkeleton()`

> <img src="https://user-images.githubusercontent.com/17746153/106696623-1b7e3100-65ab-11eb-8ad2-8e5dba1c05db.jpeg" width="200">

Can you please provide more information about your problem?

**Comment by 15189611** [comment]
i mean you don't setting   android:layout_height="120dp"

**Comment by 15189611** [comment]
like this        <com.google.android.material.imageview.ShapeableImageView
            android:id="@+id/ivMap"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:scaleType="centerCrop"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:shapeAppearanceOverlay="@style/ShapeAppearance.RoundedCornerImageView"
            tools:srcCompat="@drawable/map_one" />

**Comment by ericktijerou** [comment]
@15189611 In this case your ShapeableImageView is not visible because bottom constraint is missing. 

> You can actually set width and height to `0dp` and set either top and bottom or left and right constraints to "parent".

There are two options:

- Add missing constraint:
```
        <com.google.android.material.imageview.ShapeableImageView
            android:id="@+id/ivMap"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:scaleType="centerCrop"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="@id/guideline"
            app:shapeAppearanceOverlay="@style/ShapeAppearance.RoundedCornerImageView"
            tools:srcCompat="@drawable/map_one" />

        <androidx.constraintlayout.widget.Guideline
            android:id="@+id/guideline"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintGuide_percent="0.4"
            android:orientation="horizontal"/>
```

- Set `android:layout_height="wrap_content"` and `app:srcCompat="@drawable/map_one"` and set the new image when you have data from network

```
        <com.google.android.material.imageview.ShapeableImageView
            android:id="@+id/ivMap"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:scaleType="centerCrop"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:shapeAppearanceOverlay="@style/ShapeAppearance.RoundedCornerImageView"
            app:srcCompat="@drawable/map_one" />
```

Have a nice day 👋
