### ISSUE TITLE
[Feature Request] - @ColorInt support

### ISSUE THREAD

**Issue by TurKurT656** [ericktijerou/koleton#29]
I've a BindingAdapter for setting skeleton:
```
@BindingAdapter(
        "binding:loadSkeleton",
        "binding:skeletonLength",
        "binding:skeletonCornerRadius",
        requireAll = false
    )
    @JvmStatic
    fun loadSkeleton(
        textView: TextView,
        loadSkeleton: Boolean,
        skeletonLength: Int?, // Default is 5
        skeletonCornerRadius: Float?, // Default is 8
    ) {
        val sLength = skeletonLength ?: 5
        val sCornerRadius = skeletonCornerRadius ?: 8f
        if (loadSkeleton)
            textView.loadSkeleton(sLength) {
                cornerRadius(sCornerRadius)
                color(R.color.my_custom_color)
            }
        else
            textView.hideSkeleton()
    }
```
Now I want to add an attribute to change the color of skeleton. Koleton doesn't support @ColorInt and only works with @ColorRes and because of that I have to import R class inside my xml files which is not a good practice. But If koleton supports ColorInt I can simply change my color with this code:
```
<TextView
    ...
    binding:skeletonColor="@{@color/my_custom_color}" />
```

**Comment by ericktijerou** [comment]
@TurKurT656 I've created a new method `fun colorInt(@ColorInt color: Int)` in SkeletonBuilder and SkeletonLoader. Please try out `0.8.8` version, let me know if your issue has been resolved.

Have a nice day!

**Comment by TurKurT656** [comment]
Thanks, Yes it worked
