### ISSUE TITLE
[Feature Request] - add loading length to TextViewKoleton 

### ISSUE THREAD

**Issue by TurKurT656** [ericktijerou/koleton#8]
The problem is  that sometimes the TextView's text is coming from api call and until that the text is empty and when I set skeleton on it the skeleton is not visible. I can set a dummy text on it until network response but I think this is an ugly solution. 
It would be great if We can add an option to set a loading length on TextView skeleton.

**Comment by ericktijerou** [comment]
Hi @TurKurT656 👋,

It is not necessary to set text in your xml. You just have to set length for skeleton to work well.

`textView?.loadSkeleton(length = 20)
`

Please try out `0.8.5` version.

**Comment by TurKurT656** [comment]
Thank you a lot
